[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.default]
solc = '0.8.23'
src = 'solidity'
test = 'solidity/test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
fs_permissions = [{ access = "read-write", path = "./"}]

[profile.test]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000
src = 'solidity/test'
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
  mainnet = "${ETHEREUM_MAINNET_RPC}"
  optimism = "${OPTIMISM_RPC_URL}"
  arbitrum = "${ARBITRUM_RPC_URL}"
  base = "${BASE_RPC_URL}"
  sepolia = "${SEPOLIA_RPC_URL}"
  arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"
  base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
  optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

[etherscan]
  mainnet = { key = "${API_KEY_ETHERSCAN}" }
  arbitrum = { key = "${API_KEY_ARBISCAN}", url = "https://api.arbiscan.io/api" }
  base = { key = "${API_KEY_BASESCAN}", url = "https://api.basescan.org/api" }
  optimism = { key = "${API_KEY_OPTISCAN}", url = "https://api-optimistic.etherscan.io/api" }
  sepolia = { key = "${API_KEY_ETHERSCAN}" }
  arbitrum-sepolia = { key = "${API_KEY_ARBISCAN}", url = "https://api-sepolia.arbiscan.io/api" }
  base-sepolia = { key = "${API_KEY_BASESCAN}", url = "https://api-sepolia.basescan.org/api" }
  optimism-sepolia = { key = "${API_KEY_OPTISCAN}", url = "https://api-sepolia-optimistic.etherscan.io/api" }
